name: Schedule Test

on:
  workflow_dispatch:

  schedule:
    - cron: "7,22,37,52 * * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar información
        run: |
          echo "El workflow automático se ejecutó correctamente"
          echo "Evento: ${{ github.event_name }}"
          echo "Fecha y hora UTC:"
          date -u
