name: Update TAIKO Stats

on:
  workflow_dispatch:

  schedule:
    - cron: "17 0 * * 0"

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send Discord dashboard
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Guardar historial de eficiencia
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+users.noreply.github.com"

          git add squad_history.json weekly_history.json
          git diff --cached --quiet || git commit -m "chore: update squad performance history"
          git push origin main